//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWJ.Expressions.Xml {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWJ.Expressions.Xml.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute Empty 的本地化字符串。
        /// </summary>
        internal static string Parse_AttributeEmpty {
            get {
                return ResourceManager.GetString("Parse_AttributeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Attribute 的本地化字符串。
        /// </summary>
        internal static string Parse_AttributeError {
            get {
                return ResourceManager.GetString("Parse_AttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute Name: {0} 的本地化字符串。
        /// </summary>
        internal static string Parse_AttributeName {
            get {
                return ResourceManager.GetString("Parse_AttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child Node Name: {0} 的本地化字符串。
        /// </summary>
        internal static string Parse_ChildNodeName {
            get {
                return ResourceManager.GetString("Parse_ChildNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert Type: {0} 的本地化字符串。
        /// </summary>
        internal static string Parse_ConvertTypeName {
            get {
                return ResourceManager.GetString("Parse_ConvertTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Format 的本地化字符串。
        /// </summary>
        internal static string Parse_InvalidConvert {
            get {
                return ResourceManager.GetString("Parse_InvalidConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Node Name 的本地化字符串。
        /// </summary>
        internal static string Parse_InvalidNodeName {
            get {
                return ResourceManager.GetString("Parse_InvalidNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requires Node Attribute 的本地化字符串。
        /// </summary>
        internal static string Parse_MissingAttribute {
            get {
                return ResourceManager.GetString("Parse_MissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requires Child Node 的本地化字符串。
        /// </summary>
        internal static string Parse_MissingChildNode {
            get {
                return ResourceManager.GetString("Parse_MissingChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Name: {0} 的本地化字符串。
        /// </summary>
        internal static string Parse_NodeName {
            get {
                return ResourceManager.GetString("Parse_NodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Accessable Expression Node 的本地化字符串。
        /// </summary>
        internal static string Parse_NotAccessableNode {
            get {
                return ResourceManager.GetString("Parse_NotAccessableNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Body Node 的本地化字符串。
        /// </summary>
        internal static string Parse_NotBodyNode {
            get {
                return ResourceManager.GetString("Parse_NotBodyNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Instance Or Type Node 的本地化字符串。
        /// </summary>
        internal static string Parse_NotInstanceOrTypeNode {
            get {
                return ResourceManager.GetString("Parse_NotInstanceOrTypeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Test Value Node 的本地化字符串。
        /// </summary>
        internal static string Parse_NotTestValueNode {
            get {
                return ResourceManager.GetString("Parse_NotTestValueNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parse Text: {0} 的本地化字符串。
        /// </summary>
        internal static string Parse_ParseText {
            get {
                return ResourceManager.GetString("Parse_ParseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Scope Can Only Occur Once 的本地化字符串。
        /// </summary>
        internal static string Parse_RepeatNode {
            get {
                return ResourceManager.GetString("Parse_RepeatNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requires A Child Node 的本地化字符串。
        /// </summary>
        internal static string Parse_RequiresAChildNode {
            get {
                return ResourceManager.GetString("Parse_RequiresAChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requires Two Child Nodes 的本地化字符串。
        /// </summary>
        internal static string Parse_RequiresTwoChildNode {
            get {
                return ResourceManager.GetString("Parse_RequiresTwoChildNode", resourceCulture);
            }
        }
    }
}
