//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWJ.Expressions.Xml.Test {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWJ.Expressions.Xml.Test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///  &lt;expr name=&quot;ifThen&quot; result=&quot;true&quot; resultType=&quot;bool&quot;&gt;
        ///    &lt;!--( if(true) true;)--&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:if&gt;
        ///        &lt;x:true/&gt;
        ///        &lt;x:true/&gt;
        ///      &lt;/x:if&gt;
        ///    &lt;/x:return&gt;
        ///  &lt;/expr&gt;
        ///  &lt;expr name=&quot;else&quot; result=&quot;true&quot; resultType=&quot;bool&quot;&gt;
        ///    &lt;!--(  true? true: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _if {
            get {
                return ResourceManager.GetString("_if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///
        ///  &lt;expr name=&quot;switch&quot; result=&quot;20&quot; resultType=&quot;int32&quot;&gt;
        ///    &lt;!--
        ///    int i=0,result;
        ///    switch(2){
        ///      case 1:
        ///        result=10;
        ///        break;
        ///      case 2:
        ///        result=20;
        ///        break;
        ///    }
        ///    return result;
        ///    --&gt;
        ///    &lt;x:vars&gt;
        ///      &lt;x:var ty [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _switch {
            get {
                return ResourceManager.GetString("_switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///  &lt;try&gt;
        ///    &lt;catch type=&quot;&quot;&gt;
        ///
        ///    &lt;/catch&gt;
        ///  &lt;/try&gt;
        ///
        ///&lt;/expression&gt; 的本地化字符串。
        /// </summary>
        internal static string _try {
            get {
                return ResourceManager.GetString("_try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///  &lt;test name=&quot;static min&quot; result=&quot;1&quot; resultType=&quot;int32&quot;&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:call method=&quot;staticMin&quot;&gt;
        ///        &lt;x:type&gt;LWJ.Expressions.Xml.Test.CallTest+TestClass,LWJ.Expressions.Xml.Test&lt;/x:type&gt;
        ///        &lt;x:int32&gt;1&lt;/x:int32&gt;
        ///        &lt;x:int32&gt;2&lt;/x:int32&gt;
        ///      &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string call {
            get {
                return ResourceManager.GetString("call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;test  xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///  &lt;!--
        ///  &lt;expr name=&quot;constant_int32&quot; result=&quot;1&quot; resultType=&quot;int&quot;&gt;
        ///
        ///    &lt;x:return&gt;
        ///      &lt;x:constant type=&quot;int32&quot;&gt;1&lt;/x:constant&gt;
        ///    &lt;/x:return&gt;
        ///  &lt;/expr&gt;
        ///  &lt;expr name=&quot;constant_int64&quot; result=&quot;1&quot; resultType=&quot;long&quot;&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:constant type=&quot;int64&quot;&gt;1&lt;/x:cons [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string constant {
            get {
                return ResourceManager.GetString("constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;test xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///      xmlns:my=&quot;urn:my&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///  &lt;test name=&quot;static min&quot; result=&quot;1&quot; resultType=&quot;int32&quot;&gt;
        ///    &lt;x:return&gt;
        ///      &lt;my:helloWorld/&gt;
        ///    &lt;/x:return&gt;
        ///  &lt;/test&gt;
        ///
        ///&lt;/test&gt; 的本地化字符串。
        /// </summary>
        internal static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///  &lt;test name=&quot;add&quot; result=&quot;3&quot; resultType=&quot;int32&quot;&gt;
        ///    &lt;x:func name=&quot;add&quot; returnType=&quot;int32&quot;&gt;
        ///      &lt;x:vars&gt;
        ///        &lt;x:var type=&quot;int32&quot;&gt;a&lt;/x:var&gt;
        ///        &lt;x:var type=&quot;int32&quot;&gt;b&lt;/x:var&gt;
        ///      &lt;/x:vars&gt;
        ///      &lt;x:return&gt;
        ///        &lt;x:add&gt;
        ///          &lt;x:var&gt;a&lt;/x:var&gt;
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string function {
            get {
                return ResourceManager.GetString("function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot; 
        ///            xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///            xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///  &lt;expr name=&quot;loop&quot; result=&quot;5&quot; resultType=&quot;int32&quot;&gt;
        ///    &lt;!--
        ///    int i=0;
        ///    while(true){
        ///      if(i&gt;=5) break;
        ///      i++;
        ///    }
        ///    --&gt;
        ///    &lt;x:vars&gt;
        ///      &lt;x:var  type=&quot;int32&quot; &gt;i&lt;/x:var&gt;
        ///    &lt;/x:vars&gt;
        ///    &lt;x:assign&gt;
        ///      &lt;x:var&gt;i&lt;/x:var&gt;
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string loop {
            get {
                return ResourceManager.GetString("loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///  &lt;expr name=&quot;constant_named_true&quot; result=&quot;true&quot; resultType=&quot;bool&quot;&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:true/&gt;
        ///    &lt;/x:return&gt;
        ///  &lt;/expr&gt;
        ///  &lt;expr name=&quot;constant_named_false&quot; result=&quot;false&quot; resultType=&quot;bool&quot;&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:false/&gt;
        ///    &lt;/x:return&gt;
        ///  &lt;/expr&gt;
        ///  &lt;expr  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string named_type {
            get {
                return ResourceManager.GetString("named_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///  &lt;expr name=&quot;or&quot; result=&quot;true&quot; resultType=&quot;bool&quot;&gt;
        ///    &lt;!--(false || true)--&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:or&gt;
        ///        &lt;x:false/&gt;
        ///        &lt;x:true/&gt;
        ///      &lt;/x:or&gt;
        ///    &lt;/x:return&gt;
        ///  &lt;/expr&gt;
        ///&lt;/expression&gt; 的本地化字符串。
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression  xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;&gt;
        ///
        ///  &lt;x:func name=&quot;sum&quot; returnType=&quot;int32&quot;&gt;
        ///    &lt;x:vars&gt;
        ///      &lt;x:var type=&quot;int32&quot;&gt;n&lt;/x:var&gt;
        ///    &lt;/x:vars&gt;
        ///    &lt;x:return&gt;
        ///      &lt;x:if&gt;
        ///        &lt;x:lessThanOrEqual&gt;
        ///          &lt;x:var&gt;n&lt;/x:var&gt;
        ///          &lt;x:int32&gt;1&lt;/x:int32&gt;
        ///        &lt;/x:lessThanOrEqual&gt;
        ///        &lt;x:int3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;expression xmlns:x=&quot;urn:schema-lwj:expression&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///      xsi:schemaLocation=&quot;urn:schema-lwj:expression ../../../resources/lwj.expr.xsd&quot;
        ///&gt;
        ///
        ///  &lt;expr name=&quot;get_variable&quot; result=&quot;1&quot; resultType=&quot;int32&quot;&gt;
        ///    &lt;!--
        ///    int a=1;
        ///     a;
        ///    --&gt;
        ///    &lt;x:vars&gt;
        ///      &lt;x:var type=&quot;int32&quot;&gt;a&lt;/x:var&gt;
        ///    &lt;/x:vars&gt;
        ///    &lt;x:assign&gt;
        ///      &lt;x:var&gt;a&lt;/x:var&gt;
        ///      &lt;x:int32 &gt;1&lt;/x:int32&gt;
        ///    &lt;/x:assign&gt;
        ///    &lt;x:return&gt;
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string variable {
            get {
                return ResourceManager.GetString("variable", resourceCulture);
            }
        }
    }
}
