//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWJ.Expressions {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWJ.Expressions.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Expression Exception 的本地化字符串。
        /// </summary>
        internal static string ExprException {
            get {
                return ResourceManager.GetString("ExprException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Not Found. Name: {0} 的本地化字符串。
        /// </summary>
        internal static string FieldNotFound {
            get {
                return ResourceManager.GetString("FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Not Writable. Name: {0} 的本地化字符串。
        /// </summary>
        internal static string FieldNotWritable {
            get {
                return ResourceManager.GetString("FieldNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Exception 的本地化字符串。
        /// </summary>
        internal static string FuncException {
            get {
                return ResourceManager.GetString("FuncException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Name: {0} 的本地化字符串。
        /// </summary>
        internal static string FuncName {
            get {
                return ResourceManager.GetString("FuncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Not Found 的本地化字符串。
        /// </summary>
        internal static string FuncNotFound {
            get {
                return ResourceManager.GetString("FuncNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Constant Value, Type Only (Type.IsPrimitive Or String) 的本地化字符串。
        /// </summary>
        internal static string InvalidConstantType {
            get {
                return ResourceManager.GetString("InvalidConstantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Is Static 的本地化字符串。
        /// </summary>
        internal static string MethodIsStatic {
            get {
                return ResourceManager.GetString("MethodIsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Arguments Length != 1 的本地化字符串。
        /// </summary>
        internal static string MethodNotArgs1 {
            get {
                return ResourceManager.GetString("MethodNotArgs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Arguments Length != 2 的本地化字符串。
        /// </summary>
        internal static string MethodNotArgs2 {
            get {
                return ResourceManager.GetString("MethodNotArgs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method Not Is Static 的本地化字符串。
        /// </summary>
        internal static string MethodNotStatic {
            get {
                return ResourceManager.GetString("MethodNotStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator Not Implemented 的本地化字符串。
        /// </summary>
        internal static string OperNotImpl {
            get {
                return ResourceManager.GetString("OperNotImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Not Found. Name: {0} 的本地化字符串。
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Not Readable. Name: {0} 的本地化字符串。
        /// </summary>
        internal static string PropertyNotReadable {
            get {
                return ResourceManager.GetString("PropertyNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &lt;{0}&gt; Not Writable 的本地化字符串。
        /// </summary>
        internal static string PropertyNotWritable {
            get {
                return ResourceManager.GetString("PropertyNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Or Field Not Found. Name: {0} 的本地化字符串。
        /// </summary>
        internal static string PropertyOrFieldNotFound {
            get {
                return ResourceManager.GetString("PropertyOrFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot Be A Value Type 的本地化字符串。
        /// </summary>
        internal static string TypeAsNotValueType {
            get {
                return ResourceManager.GetString("TypeAsNotValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Exception 的本地化字符串。
        /// </summary>
        internal static string VarException {
            get {
                return ResourceManager.GetString("VarException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Name: {0} 的本地化字符串。
        /// </summary>
        internal static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Not Defined 的本地化字符串。
        /// </summary>
        internal static string VariableNotFound {
            get {
                return ResourceManager.GetString("VariableNotFound", resourceCulture);
            }
        }
    }
}
